apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: bskreddy18/my-repo:latest
      ports:
        - containerPort: 8080
